argo-project:
  argo:
    readOnlyGroups:
      - grupo-redmine-ro
    adminGroups:
      - grupo-redmine-admin

    baseApplication:
      helm:
        values: |
          quota:
            requests:
              cpu: '1'
              memory: 2Gi
            limits:
              cpu: '2'
              memory: 4Gi
            pods: "5"
            persistentvolumeclaims: "3"
            resourcequotas: "1"
            services: "5"

          limits:
            default:
              cpu: 200m
              memory: 512Mi
            defaultRequest:
              cpu: 100m
              memory: 256Mi
            type: Container

    applicationRequirements:
      enabled: true
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.3.x
      chart: mariadb
      helm:
        values: |
          fullnameOverride: wp-db
          architecture: standalone
          auth:
            rootPassword: supersecret
            database: redmine
            username: redmine
            password: pass
          primary:
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            persistence:
              enabled: true
              storageClass: ""
              accessModes:
                - ReadWriteOnce
              size: 1Gi
      syncPolicy:
        automated: {}

    application:
      enabled: true
      repoURL: https://gitlab.com/mikroways/k8s/charts/gitops/redmine-deploy-testing.git
      targetRevision: HEAD
      path: .
      syncPolicy:
        automated: {}
