argo-project:
  argo:
    readOnlyGroups:
      - grupo-redmine-ro
    adminGroups:
      - grupo-redmine-admin

    baseApplication:
      helm:
        values: |
          quota:
            requests:
              cpu: '1'
              memory: 2Gi
            limits:
              cpu: '2'
              memory: 4Gi
            pods: "5"
            persistentvolumeclaims: "3"
            resourcequotas: "1"
            services: "5"

          limits:
            default:
              cpu: 200m
              memory: 512Mi
            defaultRequest:
              cpu: 100m
              memory: 256Mi
            type: Container

    applicationRequirements:
      enabled: true
      repoURL: https://gitlab.com/mikroways/k8s/charts/gitops/redmine-deploy-testing.git
      targetRevision: HEAD
      path: reqs/
      helm:
        valueFiles:
          - secrets+age-import-kubernetes://argocd/helm-secrets-age-private-key#key.txt?values-secret.yaml
      syncPolicy:
        automated: {}

    application:
      enabled: true
      repoURL: https://gitlab.com/mikroways/k8s/charts/gitops/redmine-deploy-testing.git
      targetRevision: HEAD
      path: redmine/
      helm:
        valueFiles:
          - secrets+age-import-kubernetes://argocd/helm-secrets-age-private-key#key.txt?values-secret.yaml
          - values-version.yaml
      syncPolicy:
        automated: {}
