argo-project:
  argo:
    # Si se utiliza un repositorio privado diferente al configurado en Argo CD,
    # podemos dar de alta un repositorio nuevo desde aquí mismo. Dejamos el
    # comentario para mostrar como es posible configurar un repositorio privado
    # git desde el proyecto mismo usando gitops y sin modificar la instalación
    # de Argo CD.
    # repositories:
    #   - name: my-gitlab-repo
    #     url: https://gitlab.com/chrodriguez/gitops-private-demo.git
    #     username: demo
    #     password: a super secret token from gitlab configuration
    repositories:
      - name: CHANGEME
        url: CHANGEME
        username: CHANGEME
        password: CHANGEME
    readOnlyGroups:
      - grupo-ro-01
      - grupo-ro-02
    adminGroups:
      - grupo-admin-01
    baseApplication:
      helm:
        values: |
          # dockerconfigjson puede crearse como se explica en
          # https://github.com/Mikroways/argo-gitops-flow/tree/main/charts/argo-base-app#registry-secret
          registrySecrets:
            - name: image-pull-secret
              dockerconfigjson: CHANGEME
            # Pueden setearse más imagePullSecrets y modificar luego del
            # repositorio CHANGEME el secreto usado, para ver como se integran
            # estas configuraciones. Acá dejamos dos ejemplos:
            # - name: gitlab-secret
            #   dockerconfigjson: xxxxxx
            # - name: github-secret
            #   dockerconfigjson: xxxxxx
          quota:
            requests:
              cpu: '2'
              memory: 6Gi
            limits:
              cpu: '4'
              memory: 8Gi
            pods: "10"
            persistentvolumeclaims: "5"
            resourcequotas: "1"
            services: "5"

          limits:
            default:
              cpu: 200m
              memory: 512Mi
            defaultRequest:
              cpu: 100m
              memory: 256Mi
            type: Container
    application:
      enabled: true
      # Usar el repositorio personal, que tuvo que dar permiso en la sección
      # repositories antes mencioanda.
      repoURL: CHANGEME
      # Carpeta con dentro del repositorio anterior donde reside el chart que
      # desplegará nuestra aplicación.
      path: gitops-custom-nginx/
      # Rama en este repositorio donde trabajaremos
      targetRevision: main
      syncPolicy:
        automated: {}
