argo-project:
  argo:
    # Si se utiliza un repositorio privado diferente al configurado en Argo CD,
    # podemos dar de alta un repositorio nuevo desde aquí mismo. Dejamos el
    # comentario para mostrar como es posible configurar un repositorio privado
    # git desde el proyecto mismo usando gitops y sin modificar la instalación
    # de Argo CD. Este repositorio sería el que figura en CHANGEME
    # repositories:
    #   - name: my-gitlab-repo
    #     url: https://gitlab.com/your-user/gitops-private-demo.git
    #     username: demo
    #     password: a super secret token from gitlab configuration
    readOnlyGroups:
        - grupo-ro-01
        - grupo-ro-02
    adminGroups:
        - grupo-admin-01
    baseApplication:
        helm:
            values: |
                quota:
                  requests:
                    cpu: '2'
                    memory: 6Gi
                  limits:
                    cpu: '4'
                    memory: 8Gi
                  pods: "10"
                  persistentvolumeclaims: "5"
                  resourcequotas: "1"
                  services: "5"

                limits:
                  default:
                    cpu: 200m
                    memory: 512Mi
                  defaultRequest:
                    cpu: 100m
                    memory: 256Mi
                  type: Container
    applicationRequirements:
        enabled: true
        repoURL: CHANGEME
        # Carpeta con dentro del repositorio donde están los requerimientos
        path: gitops-wordpress/reqs
        targetRevision: main
        helm:
          valueFiles:
            - secrets+age-import-kubernetes://argocd/helm-secrets-age-private-key#key.txt?secrets.yaml
        syncPolicy:
            automated: {}
    application:
        enabled: true
        repoURL: CHANGEME
        # Carpeta con dentro del repositorio donde está el chart de wp
        path: gitops-wordpress/wp
        targetRevision: main
        helm:
          valueFiles:
            - secrets+age-import-kubernetes://argocd/helm-secrets-age-private-key#key.txt?secrets.yaml
        # Descomentar las siguientes líneas promueven el uso de auto-sync.
        # Dejamos comentado para justamente no promover auto-sync del wp, sí
        # de la db instalada como requirement.
        #syncPolicy:
        #    automated: {}
