argo-project:
    argo:
        readOnlyGroups:
            - ENC[AES256_GCM,data:Mdl85ylUzM07AwA=,iv:OrtIpDxnXGdyF+oB/7D48bAFFt4Sk2c7d2b2LHuptgU=,tag:zZy7Ki4HxcP+NJwwJH760Q==,type:str]
            - ENC[AES256_GCM,data:nEU7Qu24srl4Pmk=,iv:PD7FtSzka6KURTmSpp3kl7SDcLjcKT9s2hk1PAoZ3vg=,tag:OJfv87jvr1rdFp7GoNOlJA==,type:str]
        adminGroups:
            - ENC[AES256_GCM,data:90CfK/2E9yOk0SyaDGo=,iv:PmQ6qJGaCf/qBwV24Gyhl40J3NAR6ZdE++ViQ4WZSFE=,tag:JCj7IsU88jrcVx493gcaUg==,type:str]
        baseApplication:
            helm:
                values: ENC[AES256_GCM,data:qPQVM/oT/FCMDZIqRUNMCzyllx2g00P0YgDgDgLyzjA0/6/rFpZx4nzZVDYn/oGNiHqCc8uu5nR6aIktNKTYqxSmvuy+onOd8n6B7EhC/EH3vIOHRIUlk9ksAsPCf8Y5T3z8GVYNZ7Hx6sIecZ1g47970drV2w8ms+EMJcDif01Mz4Sq/1o6MIYAObJq/qXxYN6JsKHEPhldbsZH3P9BaSernz9FWPb4iqOLPVQLpAkdbpjTf/BiawTmI1qSM/hx4cN5YVrY7X/AwarITYXyHqhRuDAaku5k8Apfjb6d64vZQD76jkEL06g+6npAtm6T/p6ddR2m/SgXaAo5oMjlSvIJUo6ksIdxmX/weN5Pm76lbAZneg5QP5tILAkuhHkM,iv:LrOkibnkWRtLLMBVoY6X6/n0uiYdcVOyVV5ewgTqcN8=,tag:wDiS18/V0m5SZBbATr+TvQ==,type:str]
        applicationRequirements:
            enabled: ENC[AES256_GCM,data:7A6+yg==,iv:w5AiTSXZxUKVIutwMG++iluvkSh0vo2vonbTuS7R8+U=,tag:MD4qDmFfEsZy+yi0HumKVA==,type:bool]
            repoURL: ENC[AES256_GCM,data:6+Xb6J26+wT+y7kRycT4TlYxlwmZ0z3uGrur73x624tWCQ==,iv:GaL1tLH8RsMjUxCg3a5Z2tffhJUSkAWNxhE0Hc4hKsk=,tag:JgP30F0Gi4AvE9hG5Vb/zA==,type:str]
            targetRevision: ENC[AES256_GCM,data:j5dqAD5o,iv:TdNfPJyVZhWUby1XYIouKkOP8GK4J/wboPQPfb2lJV4=,tag:VBSZhghJPR5xUP2qEE8Zow==,type:str]
            chart: ENC[AES256_GCM,data:stBT51q3xg==,iv:uv1/VCtDIXvvmdxpKlhRWOQJBlQk3znR8sdonZfXzd0=,tag:L87M6/MAK2Sgl9EM6TzFAw==,type:str]
            helm:
                values: ENC[AES256_GCM,data:vpW/i0+W1Dvm1c3J2calprYolHz2JLP2fxPjejc8aKZrim+JdG1wov78RgnPxL56j8vh+e5zOFPgxmwuYNlRNE8tpCjqhdkIxGung/rhxOIqnafYUowqdfYkYQXlDFRlHwk44S7+iWGCTJlSNtXaPQFFyAY2o+GXFTE18ZORsqbHZN5rtCa2nbxT3dQPW6IypOOJZtjVUclNbO6UWNAzGdrd2UCgQ/+m3w3qCRwFSwaZ6pbLV/2C/y3gfDtqv5OdCOw2p/JsGAocFTNd1A30U/8Smbg0BKKNV/ZhiFY47L9iYoO/+xmN64kOyIqOHV8P8VQhktQBou3VLnTsod6yeYWe/bvzyDyD3RE57i5GXtm7W6t+mTt2wI8hj6unzWNxMTLAMQvgGNIU9h1gcXzbKxFtS4HXNH6ojyuw43Qt7XDefvqx/cbs13uIvBBSjt+cf7p+06wadA5BEvh3hlSWrzBOOiq/qY7RzxKKsNn8w/ANog==,iv:ItD3KEL2wT8ea7tvR9oD9FOfucWwK7w5svbvytA4ULA=,tag:nwv3lv2A97WmncveJ/PrvQ==,type:str]
            syncPolicy:
                automated: {}
        application:
            enabled: ENC[AES256_GCM,data:XWELug==,iv:vvjLZWHHY3lCze3pRo5EbmY5SDCHLLFMIzzwiIKmjTw=,tag:R63xpQHNZvqlFax9cPoKbA==,type:bool]
            repoURL: ENC[AES256_GCM,data:+hYGcV/5vs+VUIg+tZGGTL81XrTurQ4+MNnHdZngH+VAVw==,iv:BvV5shoFtmfklVFq5ARlKJrT0W5TGxEIf2Qj5gozpYk=,tag:J+JC+YyaTeMaIWLf8AJBDQ==,type:str]
            targetRevision: ENC[AES256_GCM,data:YlACtxo7,iv:I5N3ucJtI7aY0ORtShzUlfpjdg6KgIUTimacrbIw0TE=,tag:raY5du4aeWAXfl+W3gOSMw==,type:str]
            chart: ENC[AES256_GCM,data:ae270zbIr/pI,iv:xKjvyxCiodAKyJIeAWEXMuFhGl0tkFtVNnp+q9GJ0rg=,tag:AaCfjpTOXJqs8tYlW3nNjg==,type:str]
            helm:
                values: ENC[AES256_GCM,data:oRtf3UuyjIxM1sxYdj5EgEsV20ZtP3s5KQ4p+pnCLIWJEyLJjJnKUMgAvlkEAY3z4H7oFb5aK09OFLKw7mhaKjcVMS+y8clm5HzGBp0bY8U8g8PBXXTbJZOstIQyg4McklpiLL7g1/ITm4LcBhyA8HvAdnMudDKj7QBmrcVH6JYoSJbtK1ruYBbMUt+HXQ+60ydXmrLVa5I3Oz8WhdT+EwE/GegXPrEhvyHD0tiIvFWaLG/BHbcTTtADQFBFU6DFTo9llBuR2kLUbY0bl9Ze0mum9hrO6PNqcD2KvDdjx926f1GRSxDzBO03em5KMlJj4m2LpWrugrdh/YMREoImKr4Ik6bOy9wnJ/cVXRwTEbRAb47+0wUe6pKVP3JkbkzD8dJRFY3fFpvvENAYI6EBb9Ya62k/XfkWal9O8zLYvzHd2pOk4JOr,iv:wMZw2EMuDt8gbA2U65w3TKnv9LS4oSEQ058a6vZx8dk=,tag:jwz1k0Q00usaJZR1Nly/Lw==,type:str]
            syncPolicy:
                automated: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age193tt38de3fzuujax2krt450mfpaf25zc957h6qp7nrp2uxzj3apsywa3sz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHRVRGVCQkFwUnEyT3Ji
            bVJ5L3J4N2IvRzFFVHpOMm00b2x6WlZJc3lNCkhzc2lkdzhNUVo0QlRmV2VLdHBI
            eUZKMnlmR1hGWENSSzMxTDRrZzh1ZDQKLS0tIE5YRXQ3NStkOVhETkVhckxhckFE
            Slh1YzBQdWQ5ZHlHcEJ5clp4SnFPVGsK6upcQS6+pov24OOBmi1WDlARxHExAY3h
            Bjl5lK03bU6dyuRa5Dai55py17pgRaSjL9qQpDNwur950IHuvESr9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T16:24:51Z"
    mac: ENC[AES256_GCM,data:RKI5gBRDYYadFmtdJpNB17o2ep8KYi6G9CYQhHlW4xew9TKxr7RCWmq/lzo21A6QjE8zrSnqymcv6INXa4BACbAkQdIZKaMBlQKkpCmwcGLKQeJdMFzYYLMeYZAxQ2bOKXfRjSaJjAQfTuNEsTQsYjMRWMcQxKMPZmK9rkpJnu4=,iv:2ZixBTcJRv5q0BIa8rKVlE+LptGjB4FiE7NHHdPt+Go=,tag:LMWZekgl6NgWZlLuD3S9Wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
