repositories:
  - name: argocd
    url: https://argoproj.github.io/argo-helm
releases:
- name: argocd
  namespace: argocd
  chart: argocd/argo-cd
  version: 6.9.*
  values:
    - values/argocd/values.yaml
  secrets:
    - values/argocd/secrets.yaml
